// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sparkplugB.proto

package sparkplugbProtobufGo

/*

To compile:
cd client_libraries/java
protoc --proto_path=../../ --java_out=src/main/java ../../sparkplug_b.proto

*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	Timestamp                    *uint64           `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Metrics                      []*Payload_Metric `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Seq                          *uint64           `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	Uuid                         *string           `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Body                         []byte            `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}          `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0}
}

var extRange_Payload = []proto.ExtensionRange{
	{Start: 6, End: 536870911},
}

func (*Payload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(dst, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Payload) GetMetrics() []*Payload_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Payload) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Payload) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Payload_Template struct {
	Version                      *string                       `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Metrics                      []*Payload_Metric             `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Parameters                   []*Payload_Template_Parameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	TemplateRef                  *string                       `protobuf:"bytes,4,opt,name=template_ref,json=templateRef" json:"template_ref,omitempty"`
	IsDefinition                 *bool                         `protobuf:"varint,5,opt,name=is_definition,json=isDefinition" json:"is_definition,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Template) Reset()         { *m = Payload_Template{} }
func (m *Payload_Template) String() string { return proto.CompactTextString(m) }
func (*Payload_Template) ProtoMessage()    {}
func (*Payload_Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 0}
}

var extRange_Payload_Template = []proto.ExtensionRange{
	{Start: 6, End: 536870911},
}

func (*Payload_Template) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Template
}
func (m *Payload_Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template.Unmarshal(m, b)
}
func (m *Payload_Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template.Marshal(b, m, deterministic)
}
func (dst *Payload_Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template.Merge(dst, src)
}
func (m *Payload_Template) XXX_Size() int {
	return xxx_messageInfo_Payload_Template.Size(m)
}
func (m *Payload_Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template proto.InternalMessageInfo

func (m *Payload_Template) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Payload_Template) GetMetrics() []*Payload_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Payload_Template) GetParameters() []*Payload_Template_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Payload_Template) GetTemplateRef() string {
	if m != nil && m.TemplateRef != nil {
		return *m.TemplateRef
	}
	return ""
}

func (m *Payload_Template) GetIsDefinition() bool {
	if m != nil && m.IsDefinition != nil {
		return *m.IsDefinition
	}
	return false
}

type Payload_Template_Parameter struct {
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_Template_Parameter_IntValue
	//	*Payload_Template_Parameter_LongValue
	//	*Payload_Template_Parameter_FloatValue
	//	*Payload_Template_Parameter_DoubleValue
	//	*Payload_Template_Parameter_BooleanValue
	//	*Payload_Template_Parameter_StringValue
	//	*Payload_Template_Parameter_ExtensionValue
	Value                isPayload_Template_Parameter_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Payload_Template_Parameter) Reset()         { *m = Payload_Template_Parameter{} }
func (m *Payload_Template_Parameter) String() string { return proto.CompactTextString(m) }
func (*Payload_Template_Parameter) ProtoMessage()    {}
func (*Payload_Template_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 0, 0}
}
func (m *Payload_Template_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template_Parameter.Unmarshal(m, b)
}
func (m *Payload_Template_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template_Parameter.Marshal(b, m, deterministic)
}
func (dst *Payload_Template_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template_Parameter.Merge(dst, src)
}
func (m *Payload_Template_Parameter) XXX_Size() int {
	return xxx_messageInfo_Payload_Template_Parameter.Size(m)
}
func (m *Payload_Template_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template_Parameter proto.InternalMessageInfo

type isPayload_Template_Parameter_Value interface {
	isPayload_Template_Parameter_Value()
}

type Payload_Template_Parameter_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}
type Payload_Template_Parameter_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}
type Payload_Template_Parameter_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}
type Payload_Template_Parameter_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}
type Payload_Template_Parameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}
type Payload_Template_Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}
type Payload_Template_Parameter_ExtensionValue struct {
	ExtensionValue *Payload_Template_Parameter_ParameterValueExtension `protobuf:"bytes,9,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Template_Parameter_IntValue) isPayload_Template_Parameter_Value()       {}
func (*Payload_Template_Parameter_LongValue) isPayload_Template_Parameter_Value()      {}
func (*Payload_Template_Parameter_FloatValue) isPayload_Template_Parameter_Value()     {}
func (*Payload_Template_Parameter_DoubleValue) isPayload_Template_Parameter_Value()    {}
func (*Payload_Template_Parameter_BooleanValue) isPayload_Template_Parameter_Value()   {}
func (*Payload_Template_Parameter_StringValue) isPayload_Template_Parameter_Value()    {}
func (*Payload_Template_Parameter_ExtensionValue) isPayload_Template_Parameter_Value() {}

func (m *Payload_Template_Parameter) GetValue() isPayload_Template_Parameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_Template_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Payload_Template_Parameter) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Payload_Template_Parameter) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_Template_Parameter) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_Template_Parameter) GetExtensionValue() *Payload_Template_Parameter_ParameterValueExtension {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Payload_Template_Parameter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Payload_Template_Parameter_OneofMarshaler, _Payload_Template_Parameter_OneofUnmarshaler, _Payload_Template_Parameter_OneofSizer, []interface{}{
		(*Payload_Template_Parameter_IntValue)(nil),
		(*Payload_Template_Parameter_LongValue)(nil),
		(*Payload_Template_Parameter_FloatValue)(nil),
		(*Payload_Template_Parameter_DoubleValue)(nil),
		(*Payload_Template_Parameter_BooleanValue)(nil),
		(*Payload_Template_Parameter_StringValue)(nil),
		(*Payload_Template_Parameter_ExtensionValue)(nil),
	}
}

func _Payload_Template_Parameter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Payload_Template_Parameter)
	// value
	switch x := m.Value.(type) {
	case *Payload_Template_Parameter_IntValue:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *Payload_Template_Parameter_LongValue:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongValue))
	case *Payload_Template_Parameter_FloatValue:
		b.EncodeVarint(5<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatValue)))
	case *Payload_Template_Parameter_DoubleValue:
		b.EncodeVarint(6<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Payload_Template_Parameter_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Payload_Template_Parameter_StringValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Payload_Template_Parameter_ExtensionValue:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExtensionValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Payload_Template_Parameter.Value has unexpected type %T", x)
	}
	return nil
}

func _Payload_Template_Parameter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Payload_Template_Parameter)
	switch tag {
	case 3: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Template_Parameter_IntValue{uint32(x)}
		return true, err
	case 4: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Template_Parameter_LongValue{x}
		return true, err
	case 5: // value.float_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Payload_Template_Parameter_FloatValue{math.Float32frombits(uint32(x))}
		return true, err
	case 6: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Payload_Template_Parameter_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 7: // value.boolean_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Template_Parameter_BooleanValue{x != 0}
		return true, err
	case 8: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Payload_Template_Parameter_StringValue{x}
		return true, err
	case 9: // value.extension_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_Template_Parameter_ParameterValueExtension)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_Template_Parameter_ExtensionValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Payload_Template_Parameter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Payload_Template_Parameter)
	// value
	switch x := m.Value.(type) {
	case *Payload_Template_Parameter_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Payload_Template_Parameter_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Payload_Template_Parameter_FloatValue:
		n += 1 // tag and wire
		n += 4
	case *Payload_Template_Parameter_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *Payload_Template_Parameter_BooleanValue:
		n += 1 // tag and wire
		n += 1
	case *Payload_Template_Parameter_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Payload_Template_Parameter_ExtensionValue:
		s := proto.Size(x.ExtensionValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Payload_Template_Parameter_ParameterValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Template_Parameter_ParameterValueExtension) Reset() {
	*m = Payload_Template_Parameter_ParameterValueExtension{}
}
func (m *Payload_Template_Parameter_ParameterValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_Template_Parameter_ParameterValueExtension) ProtoMessage() {}
func (*Payload_Template_Parameter_ParameterValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 0, 0, 0}
}

var extRange_Payload_Template_Parameter_ParameterValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_Template_Parameter_ParameterValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Template_Parameter_ParameterValueExtension
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Unmarshal(m, b)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Marshal(b, m, deterministic)
}
func (dst *Payload_Template_Parameter_ParameterValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Merge(dst, src)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Size(m)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension proto.InternalMessageInfo

type Payload_DataSet struct {
	NumOfColumns                 *uint64                `protobuf:"varint,1,opt,name=num_of_columns,json=numOfColumns" json:"num_of_columns,omitempty"`
	Columns                      []string               `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
	Types                        []uint32               `protobuf:"varint,3,rep,name=types" json:"types,omitempty"`
	Rows                         []*Payload_DataSet_Row `protobuf:"bytes,4,rep,name=rows" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}               `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet) Reset()         { *m = Payload_DataSet{} }
func (m *Payload_DataSet) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet) ProtoMessage()    {}
func (*Payload_DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 1}
}

var extRange_Payload_DataSet = []proto.ExtensionRange{
	{Start: 5, End: 536870911},
}

func (*Payload_DataSet) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet
}
func (m *Payload_DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet.Unmarshal(m, b)
}
func (m *Payload_DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet.Marshal(b, m, deterministic)
}
func (dst *Payload_DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet.Merge(dst, src)
}
func (m *Payload_DataSet) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet.Size(m)
}
func (m *Payload_DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet proto.InternalMessageInfo

func (m *Payload_DataSet) GetNumOfColumns() uint64 {
	if m != nil && m.NumOfColumns != nil {
		return *m.NumOfColumns
	}
	return 0
}

func (m *Payload_DataSet) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Payload_DataSet) GetTypes() []uint32 {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Payload_DataSet) GetRows() []*Payload_DataSet_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Payload_DataSet_DataSetValue struct {
	// Types that are valid to be assigned to Value:
	//	*Payload_DataSet_DataSetValue_IntValue
	//	*Payload_DataSet_DataSetValue_LongValue
	//	*Payload_DataSet_DataSetValue_FloatValue
	//	*Payload_DataSet_DataSetValue_DoubleValue
	//	*Payload_DataSet_DataSetValue_BooleanValue
	//	*Payload_DataSet_DataSetValue_StringValue
	//	*Payload_DataSet_DataSetValue_ExtensionValue
	Value                isPayload_DataSet_DataSetValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Payload_DataSet_DataSetValue) Reset()         { *m = Payload_DataSet_DataSetValue{} }
func (m *Payload_DataSet_DataSetValue) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet_DataSetValue) ProtoMessage()    {}
func (*Payload_DataSet_DataSetValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 1, 0}
}
func (m *Payload_DataSet_DataSetValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Unmarshal(m, b)
}
func (m *Payload_DataSet_DataSetValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Marshal(b, m, deterministic)
}
func (dst *Payload_DataSet_DataSetValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_DataSetValue.Merge(dst, src)
}
func (m *Payload_DataSet_DataSetValue) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Size(m)
}
func (m *Payload_DataSet_DataSetValue) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_DataSetValue.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_DataSetValue proto.InternalMessageInfo

type isPayload_DataSet_DataSetValue_Value interface {
	isPayload_DataSet_DataSetValue_Value()
}

type Payload_DataSet_DataSetValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,1,opt,name=int_value,json=intValue,oneof"`
}
type Payload_DataSet_DataSetValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,2,opt,name=long_value,json=longValue,oneof"`
}
type Payload_DataSet_DataSetValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,oneof"`
}
type Payload_DataSet_DataSetValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,oneof"`
}
type Payload_DataSet_DataSetValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,5,opt,name=boolean_value,json=booleanValue,oneof"`
}
type Payload_DataSet_DataSetValue_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,oneof"`
}
type Payload_DataSet_DataSetValue_ExtensionValue struct {
	ExtensionValue *Payload_DataSet_DataSetValue_DataSetValueExtension `protobuf:"bytes,7,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_DataSet_DataSetValue_IntValue) isPayload_DataSet_DataSetValue_Value()       {}
func (*Payload_DataSet_DataSetValue_LongValue) isPayload_DataSet_DataSetValue_Value()      {}
func (*Payload_DataSet_DataSetValue_FloatValue) isPayload_DataSet_DataSetValue_Value()     {}
func (*Payload_DataSet_DataSetValue_DoubleValue) isPayload_DataSet_DataSetValue_Value()    {}
func (*Payload_DataSet_DataSetValue_BooleanValue) isPayload_DataSet_DataSetValue_Value()   {}
func (*Payload_DataSet_DataSetValue_StringValue) isPayload_DataSet_DataSetValue_Value()    {}
func (*Payload_DataSet_DataSetValue_ExtensionValue) isPayload_DataSet_DataSetValue_Value() {}

func (m *Payload_DataSet_DataSetValue) GetValue() isPayload_DataSet_DataSetValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_DataSet_DataSetValue) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_DataSet_DataSetValue) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_DataSet_DataSetValue) GetExtensionValue() *Payload_DataSet_DataSetValue_DataSetValueExtension {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Payload_DataSet_DataSetValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Payload_DataSet_DataSetValue_OneofMarshaler, _Payload_DataSet_DataSetValue_OneofUnmarshaler, _Payload_DataSet_DataSetValue_OneofSizer, []interface{}{
		(*Payload_DataSet_DataSetValue_IntValue)(nil),
		(*Payload_DataSet_DataSetValue_LongValue)(nil),
		(*Payload_DataSet_DataSetValue_FloatValue)(nil),
		(*Payload_DataSet_DataSetValue_DoubleValue)(nil),
		(*Payload_DataSet_DataSetValue_BooleanValue)(nil),
		(*Payload_DataSet_DataSetValue_StringValue)(nil),
		(*Payload_DataSet_DataSetValue_ExtensionValue)(nil),
	}
}

func _Payload_DataSet_DataSetValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Payload_DataSet_DataSetValue)
	// value
	switch x := m.Value.(type) {
	case *Payload_DataSet_DataSetValue_IntValue:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *Payload_DataSet_DataSetValue_LongValue:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongValue))
	case *Payload_DataSet_DataSetValue_FloatValue:
		b.EncodeVarint(3<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatValue)))
	case *Payload_DataSet_DataSetValue_DoubleValue:
		b.EncodeVarint(4<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Payload_DataSet_DataSetValue_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Payload_DataSet_DataSetValue_StringValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Payload_DataSet_DataSetValue_ExtensionValue:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExtensionValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Payload_DataSet_DataSetValue.Value has unexpected type %T", x)
	}
	return nil
}

func _Payload_DataSet_DataSetValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Payload_DataSet_DataSetValue)
	switch tag {
	case 1: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_DataSet_DataSetValue_IntValue{uint32(x)}
		return true, err
	case 2: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_DataSet_DataSetValue_LongValue{x}
		return true, err
	case 3: // value.float_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Payload_DataSet_DataSetValue_FloatValue{math.Float32frombits(uint32(x))}
		return true, err
	case 4: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Payload_DataSet_DataSetValue_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 5: // value.boolean_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_DataSet_DataSetValue_BooleanValue{x != 0}
		return true, err
	case 6: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Payload_DataSet_DataSetValue_StringValue{x}
		return true, err
	case 7: // value.extension_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_DataSet_DataSetValue_DataSetValueExtension)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_DataSet_DataSetValue_ExtensionValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Payload_DataSet_DataSetValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Payload_DataSet_DataSetValue)
	// value
	switch x := m.Value.(type) {
	case *Payload_DataSet_DataSetValue_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Payload_DataSet_DataSetValue_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Payload_DataSet_DataSetValue_FloatValue:
		n += 1 // tag and wire
		n += 4
	case *Payload_DataSet_DataSetValue_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *Payload_DataSet_DataSetValue_BooleanValue:
		n += 1 // tag and wire
		n += 1
	case *Payload_DataSet_DataSetValue_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Payload_DataSet_DataSetValue_ExtensionValue:
		s := proto.Size(x.ExtensionValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Payload_DataSet_DataSetValue_DataSetValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) Reset() {
	*m = Payload_DataSet_DataSetValue_DataSetValueExtension{}
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_DataSet_DataSetValue_DataSetValueExtension) ProtoMessage() {}
func (*Payload_DataSet_DataSetValue_DataSetValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 1, 0, 0}
}

var extRange_Payload_DataSet_DataSetValue_DataSetValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_DataSet_DataSetValue_DataSetValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet_DataSetValue_DataSetValueExtension
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Unmarshal(m, b)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Marshal(b, m, deterministic)
}
func (dst *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Merge(dst, src)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Size(m)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension proto.InternalMessageInfo

type Payload_DataSet_Row struct {
	Elements                     []*Payload_DataSet_DataSetValue `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                        `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet_Row) Reset()         { *m = Payload_DataSet_Row{} }
func (m *Payload_DataSet_Row) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet_Row) ProtoMessage()    {}
func (*Payload_DataSet_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 1, 1}
}

var extRange_Payload_DataSet_Row = []proto.ExtensionRange{
	{Start: 2, End: 536870911},
}

func (*Payload_DataSet_Row) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet_Row
}
func (m *Payload_DataSet_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_Row.Unmarshal(m, b)
}
func (m *Payload_DataSet_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_Row.Marshal(b, m, deterministic)
}
func (dst *Payload_DataSet_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_Row.Merge(dst, src)
}
func (m *Payload_DataSet_Row) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_Row.Size(m)
}
func (m *Payload_DataSet_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_Row proto.InternalMessageInfo

func (m *Payload_DataSet_Row) GetElements() []*Payload_DataSet_DataSetValue {
	if m != nil {
		return m.Elements
	}
	return nil
}

type Payload_PropertyValue struct {
	Type   *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	IsNull *bool   `protobuf:"varint,2,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_PropertyValue_IntValue
	//	*Payload_PropertyValue_LongValue
	//	*Payload_PropertyValue_FloatValue
	//	*Payload_PropertyValue_DoubleValue
	//	*Payload_PropertyValue_BooleanValue
	//	*Payload_PropertyValue_StringValue
	//	*Payload_PropertyValue_PropertysetValue
	//	*Payload_PropertyValue_PropertysetsValue
	//	*Payload_PropertyValue_ExtensionValue
	Value                isPayload_PropertyValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Payload_PropertyValue) Reset()         { *m = Payload_PropertyValue{} }
func (m *Payload_PropertyValue) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertyValue) ProtoMessage()    {}
func (*Payload_PropertyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 2}
}
func (m *Payload_PropertyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertyValue.Unmarshal(m, b)
}
func (m *Payload_PropertyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertyValue.Marshal(b, m, deterministic)
}
func (dst *Payload_PropertyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertyValue.Merge(dst, src)
}
func (m *Payload_PropertyValue) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertyValue.Size(m)
}
func (m *Payload_PropertyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertyValue.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertyValue proto.InternalMessageInfo

type isPayload_PropertyValue_Value interface {
	isPayload_PropertyValue_Value()
}

type Payload_PropertyValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}
type Payload_PropertyValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}
type Payload_PropertyValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}
type Payload_PropertyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}
type Payload_PropertyValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}
type Payload_PropertyValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}
type Payload_PropertyValue_PropertysetValue struct {
	PropertysetValue *Payload_PropertySet `protobuf:"bytes,9,opt,name=propertyset_value,json=propertysetValue,oneof"`
}
type Payload_PropertyValue_PropertysetsValue struct {
	PropertysetsValue *Payload_PropertySetList `protobuf:"bytes,10,opt,name=propertysets_value,json=propertysetsValue,oneof"`
}
type Payload_PropertyValue_ExtensionValue struct {
	ExtensionValue *Payload_PropertyValue_PropertyValueExtension `protobuf:"bytes,11,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_PropertyValue_IntValue) isPayload_PropertyValue_Value()          {}
func (*Payload_PropertyValue_LongValue) isPayload_PropertyValue_Value()         {}
func (*Payload_PropertyValue_FloatValue) isPayload_PropertyValue_Value()        {}
func (*Payload_PropertyValue_DoubleValue) isPayload_PropertyValue_Value()       {}
func (*Payload_PropertyValue_BooleanValue) isPayload_PropertyValue_Value()      {}
func (*Payload_PropertyValue_StringValue) isPayload_PropertyValue_Value()       {}
func (*Payload_PropertyValue_PropertysetValue) isPayload_PropertyValue_Value()  {}
func (*Payload_PropertyValue_PropertysetsValue) isPayload_PropertyValue_Value() {}
func (*Payload_PropertyValue_ExtensionValue) isPayload_PropertyValue_Value()    {}

func (m *Payload_PropertyValue) GetValue() isPayload_PropertyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_PropertyValue) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Payload_PropertyValue) GetIsNull() bool {
	if m != nil && m.IsNull != nil {
		return *m.IsNull
	}
	return false
}

func (m *Payload_PropertyValue) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_PropertyValue_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_PropertyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_PropertyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_PropertyValue) GetPropertysetValue() *Payload_PropertySet {
	if x, ok := m.GetValue().(*Payload_PropertyValue_PropertysetValue); ok {
		return x.PropertysetValue
	}
	return nil
}

func (m *Payload_PropertyValue) GetPropertysetsValue() *Payload_PropertySetList {
	if x, ok := m.GetValue().(*Payload_PropertyValue_PropertysetsValue); ok {
		return x.PropertysetsValue
	}
	return nil
}

func (m *Payload_PropertyValue) GetExtensionValue() *Payload_PropertyValue_PropertyValueExtension {
	if x, ok := m.GetValue().(*Payload_PropertyValue_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Payload_PropertyValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Payload_PropertyValue_OneofMarshaler, _Payload_PropertyValue_OneofUnmarshaler, _Payload_PropertyValue_OneofSizer, []interface{}{
		(*Payload_PropertyValue_IntValue)(nil),
		(*Payload_PropertyValue_LongValue)(nil),
		(*Payload_PropertyValue_FloatValue)(nil),
		(*Payload_PropertyValue_DoubleValue)(nil),
		(*Payload_PropertyValue_BooleanValue)(nil),
		(*Payload_PropertyValue_StringValue)(nil),
		(*Payload_PropertyValue_PropertysetValue)(nil),
		(*Payload_PropertyValue_PropertysetsValue)(nil),
		(*Payload_PropertyValue_ExtensionValue)(nil),
	}
}

func _Payload_PropertyValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Payload_PropertyValue)
	// value
	switch x := m.Value.(type) {
	case *Payload_PropertyValue_IntValue:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *Payload_PropertyValue_LongValue:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongValue))
	case *Payload_PropertyValue_FloatValue:
		b.EncodeVarint(5<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatValue)))
	case *Payload_PropertyValue_DoubleValue:
		b.EncodeVarint(6<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Payload_PropertyValue_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Payload_PropertyValue_StringValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Payload_PropertyValue_PropertysetValue:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PropertysetValue); err != nil {
			return err
		}
	case *Payload_PropertyValue_PropertysetsValue:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PropertysetsValue); err != nil {
			return err
		}
	case *Payload_PropertyValue_ExtensionValue:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExtensionValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Payload_PropertyValue.Value has unexpected type %T", x)
	}
	return nil
}

func _Payload_PropertyValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Payload_PropertyValue)
	switch tag {
	case 3: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_PropertyValue_IntValue{uint32(x)}
		return true, err
	case 4: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_PropertyValue_LongValue{x}
		return true, err
	case 5: // value.float_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Payload_PropertyValue_FloatValue{math.Float32frombits(uint32(x))}
		return true, err
	case 6: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Payload_PropertyValue_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 7: // value.boolean_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_PropertyValue_BooleanValue{x != 0}
		return true, err
	case 8: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Payload_PropertyValue_StringValue{x}
		return true, err
	case 9: // value.propertyset_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_PropertySet)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_PropertyValue_PropertysetValue{msg}
		return true, err
	case 10: // value.propertysets_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_PropertySetList)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_PropertyValue_PropertysetsValue{msg}
		return true, err
	case 11: // value.extension_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_PropertyValue_PropertyValueExtension)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_PropertyValue_ExtensionValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Payload_PropertyValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Payload_PropertyValue)
	// value
	switch x := m.Value.(type) {
	case *Payload_PropertyValue_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Payload_PropertyValue_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Payload_PropertyValue_FloatValue:
		n += 1 // tag and wire
		n += 4
	case *Payload_PropertyValue_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *Payload_PropertyValue_BooleanValue:
		n += 1 // tag and wire
		n += 1
	case *Payload_PropertyValue_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Payload_PropertyValue_PropertysetValue:
		s := proto.Size(x.PropertysetValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Payload_PropertyValue_PropertysetsValue:
		s := proto.Size(x.PropertysetsValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Payload_PropertyValue_ExtensionValue:
		s := proto.Size(x.ExtensionValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Payload_PropertyValue_PropertyValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertyValue_PropertyValueExtension) Reset() {
	*m = Payload_PropertyValue_PropertyValueExtension{}
}
func (m *Payload_PropertyValue_PropertyValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_PropertyValue_PropertyValueExtension) ProtoMessage() {}
func (*Payload_PropertyValue_PropertyValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 2, 0}
}

var extRange_Payload_PropertyValue_PropertyValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_PropertyValue_PropertyValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertyValue_PropertyValueExtension
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Unmarshal(m, b)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Marshal(b, m, deterministic)
}
func (dst *Payload_PropertyValue_PropertyValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Merge(dst, src)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Size(m)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension proto.InternalMessageInfo

type Payload_PropertySet struct {
	Keys                         []string                 `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Values                       []*Payload_PropertyValue `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                 `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertySet) Reset()         { *m = Payload_PropertySet{} }
func (m *Payload_PropertySet) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertySet) ProtoMessage()    {}
func (*Payload_PropertySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 3}
}

var extRange_Payload_PropertySet = []proto.ExtensionRange{
	{Start: 3, End: 536870911},
}

func (*Payload_PropertySet) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertySet
}
func (m *Payload_PropertySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertySet.Unmarshal(m, b)
}
func (m *Payload_PropertySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertySet.Marshal(b, m, deterministic)
}
func (dst *Payload_PropertySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertySet.Merge(dst, src)
}
func (m *Payload_PropertySet) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertySet.Size(m)
}
func (m *Payload_PropertySet) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertySet.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertySet proto.InternalMessageInfo

func (m *Payload_PropertySet) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Payload_PropertySet) GetValues() []*Payload_PropertyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type Payload_PropertySetList struct {
	Propertyset                  []*Payload_PropertySet `protobuf:"bytes,1,rep,name=propertyset" json:"propertyset,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}               `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertySetList) Reset()         { *m = Payload_PropertySetList{} }
func (m *Payload_PropertySetList) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertySetList) ProtoMessage()    {}
func (*Payload_PropertySetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 4}
}

var extRange_Payload_PropertySetList = []proto.ExtensionRange{
	{Start: 2, End: 536870911},
}

func (*Payload_PropertySetList) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertySetList
}
func (m *Payload_PropertySetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertySetList.Unmarshal(m, b)
}
func (m *Payload_PropertySetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertySetList.Marshal(b, m, deterministic)
}
func (dst *Payload_PropertySetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertySetList.Merge(dst, src)
}
func (m *Payload_PropertySetList) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertySetList.Size(m)
}
func (m *Payload_PropertySetList) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertySetList.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertySetList proto.InternalMessageInfo

func (m *Payload_PropertySetList) GetPropertyset() []*Payload_PropertySet {
	if m != nil {
		return m.Propertyset
	}
	return nil
}

type Payload_MetaData struct {
	// Bytes specific metadata
	IsMultiPart *bool `protobuf:"varint,1,opt,name=is_multi_part,json=isMultiPart" json:"is_multi_part,omitempty"`
	// General metadata
	ContentType *string `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Size        *uint64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Seq         *uint64 `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	// File metadata
	FileName *string `protobuf:"bytes,5,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FileType *string `protobuf:"bytes,6,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
	Md5      *string `protobuf:"bytes,7,opt,name=md5" json:"md5,omitempty"`
	// Catchalls and future expansion
	Description                  *string  `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_MetaData) Reset()         { *m = Payload_MetaData{} }
func (m *Payload_MetaData) String() string { return proto.CompactTextString(m) }
func (*Payload_MetaData) ProtoMessage()    {}
func (*Payload_MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 5}
}

var extRange_Payload_MetaData = []proto.ExtensionRange{
	{Start: 9, End: 536870911},
}

func (*Payload_MetaData) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_MetaData
}
func (m *Payload_MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_MetaData.Unmarshal(m, b)
}
func (m *Payload_MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_MetaData.Marshal(b, m, deterministic)
}
func (dst *Payload_MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_MetaData.Merge(dst, src)
}
func (m *Payload_MetaData) XXX_Size() int {
	return xxx_messageInfo_Payload_MetaData.Size(m)
}
func (m *Payload_MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_MetaData proto.InternalMessageInfo

func (m *Payload_MetaData) GetIsMultiPart() bool {
	if m != nil && m.IsMultiPart != nil {
		return *m.IsMultiPart
	}
	return false
}

func (m *Payload_MetaData) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *Payload_MetaData) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Payload_MetaData) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Payload_MetaData) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *Payload_MetaData) GetFileType() string {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return ""
}

func (m *Payload_MetaData) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *Payload_MetaData) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type Payload_Metric struct {
	Name         *string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Alias        *uint64              `protobuf:"varint,2,opt,name=alias" json:"alias,omitempty"`
	Timestamp    *uint64              `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Datatype     *uint32              `protobuf:"varint,4,opt,name=datatype" json:"datatype,omitempty"`
	IsHistorical *bool                `protobuf:"varint,5,opt,name=is_historical,json=isHistorical" json:"is_historical,omitempty"`
	IsTransient  *bool                `protobuf:"varint,6,opt,name=is_transient,json=isTransient" json:"is_transient,omitempty"`
	IsNull       *bool                `protobuf:"varint,7,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	Metadata     *Payload_MetaData    `protobuf:"bytes,8,opt,name=metadata" json:"metadata,omitempty"`
	Properties   *Payload_PropertySet `protobuf:"bytes,9,opt,name=properties" json:"properties,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_Metric_IntValue
	//	*Payload_Metric_LongValue
	//	*Payload_Metric_FloatValue
	//	*Payload_Metric_DoubleValue
	//	*Payload_Metric_BooleanValue
	//	*Payload_Metric_StringValue
	//	*Payload_Metric_BytesValue
	//	*Payload_Metric_DatasetValue
	//	*Payload_Metric_TemplateValue
	//	*Payload_Metric_ExtensionValue
	Value                isPayload_Metric_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Payload_Metric) Reset()         { *m = Payload_Metric{} }
func (m *Payload_Metric) String() string { return proto.CompactTextString(m) }
func (*Payload_Metric) ProtoMessage()    {}
func (*Payload_Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 6}
}
func (m *Payload_Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Metric.Unmarshal(m, b)
}
func (m *Payload_Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Metric.Marshal(b, m, deterministic)
}
func (dst *Payload_Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Metric.Merge(dst, src)
}
func (m *Payload_Metric) XXX_Size() int {
	return xxx_messageInfo_Payload_Metric.Size(m)
}
func (m *Payload_Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Metric proto.InternalMessageInfo

type isPayload_Metric_Value interface {
	isPayload_Metric_Value()
}

type Payload_Metric_IntValue struct {
	IntValue uint32 `protobuf:"varint,10,opt,name=int_value,json=intValue,oneof"`
}
type Payload_Metric_LongValue struct {
	LongValue uint64 `protobuf:"varint,11,opt,name=long_value,json=longValue,oneof"`
}
type Payload_Metric_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,12,opt,name=float_value,json=floatValue,oneof"`
}
type Payload_Metric_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,13,opt,name=double_value,json=doubleValue,oneof"`
}
type Payload_Metric_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,14,opt,name=boolean_value,json=booleanValue,oneof"`
}
type Payload_Metric_StringValue struct {
	StringValue string `protobuf:"bytes,15,opt,name=string_value,json=stringValue,oneof"`
}
type Payload_Metric_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,oneof"`
}
type Payload_Metric_DatasetValue struct {
	DatasetValue *Payload_DataSet `protobuf:"bytes,17,opt,name=dataset_value,json=datasetValue,oneof"`
}
type Payload_Metric_TemplateValue struct {
	TemplateValue *Payload_Template `protobuf:"bytes,18,opt,name=template_value,json=templateValue,oneof"`
}
type Payload_Metric_ExtensionValue struct {
	ExtensionValue *Payload_Metric_MetricValueExtension `protobuf:"bytes,19,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Metric_IntValue) isPayload_Metric_Value()       {}
func (*Payload_Metric_LongValue) isPayload_Metric_Value()      {}
func (*Payload_Metric_FloatValue) isPayload_Metric_Value()     {}
func (*Payload_Metric_DoubleValue) isPayload_Metric_Value()    {}
func (*Payload_Metric_BooleanValue) isPayload_Metric_Value()   {}
func (*Payload_Metric_StringValue) isPayload_Metric_Value()    {}
func (*Payload_Metric_BytesValue) isPayload_Metric_Value()     {}
func (*Payload_Metric_DatasetValue) isPayload_Metric_Value()   {}
func (*Payload_Metric_TemplateValue) isPayload_Metric_Value()  {}
func (*Payload_Metric_ExtensionValue) isPayload_Metric_Value() {}

func (m *Payload_Metric) GetValue() isPayload_Metric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_Metric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Payload_Metric) GetAlias() uint64 {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return 0
}

func (m *Payload_Metric) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Payload_Metric) GetDatatype() uint32 {
	if m != nil && m.Datatype != nil {
		return *m.Datatype
	}
	return 0
}

func (m *Payload_Metric) GetIsHistorical() bool {
	if m != nil && m.IsHistorical != nil {
		return *m.IsHistorical
	}
	return false
}

func (m *Payload_Metric) GetIsTransient() bool {
	if m != nil && m.IsTransient != nil {
		return *m.IsTransient
	}
	return false
}

func (m *Payload_Metric) GetIsNull() bool {
	if m != nil && m.IsNull != nil {
		return *m.IsNull
	}
	return false
}

func (m *Payload_Metric) GetMetadata() *Payload_MetaData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Payload_Metric) GetProperties() *Payload_PropertySet {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Payload_Metric) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_Metric_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_Metric) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_Metric_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_Metric) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_Metric_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_Metric) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_Metric_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_Metric) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_Metric_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_Metric) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_Metric_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_Metric) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Payload_Metric_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Payload_Metric) GetDatasetValue() *Payload_DataSet {
	if x, ok := m.GetValue().(*Payload_Metric_DatasetValue); ok {
		return x.DatasetValue
	}
	return nil
}

func (m *Payload_Metric) GetTemplateValue() *Payload_Template {
	if x, ok := m.GetValue().(*Payload_Metric_TemplateValue); ok {
		return x.TemplateValue
	}
	return nil
}

func (m *Payload_Metric) GetExtensionValue() *Payload_Metric_MetricValueExtension {
	if x, ok := m.GetValue().(*Payload_Metric_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Payload_Metric) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Payload_Metric_OneofMarshaler, _Payload_Metric_OneofUnmarshaler, _Payload_Metric_OneofSizer, []interface{}{
		(*Payload_Metric_IntValue)(nil),
		(*Payload_Metric_LongValue)(nil),
		(*Payload_Metric_FloatValue)(nil),
		(*Payload_Metric_DoubleValue)(nil),
		(*Payload_Metric_BooleanValue)(nil),
		(*Payload_Metric_StringValue)(nil),
		(*Payload_Metric_BytesValue)(nil),
		(*Payload_Metric_DatasetValue)(nil),
		(*Payload_Metric_TemplateValue)(nil),
		(*Payload_Metric_ExtensionValue)(nil),
	}
}

func _Payload_Metric_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Payload_Metric)
	// value
	switch x := m.Value.(type) {
	case *Payload_Metric_IntValue:
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *Payload_Metric_LongValue:
		b.EncodeVarint(11<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongValue))
	case *Payload_Metric_FloatValue:
		b.EncodeVarint(12<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatValue)))
	case *Payload_Metric_DoubleValue:
		b.EncodeVarint(13<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Payload_Metric_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(14<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Payload_Metric_StringValue:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Payload_Metric_BytesValue:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.BytesValue)
	case *Payload_Metric_DatasetValue:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DatasetValue); err != nil {
			return err
		}
	case *Payload_Metric_TemplateValue:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TemplateValue); err != nil {
			return err
		}
	case *Payload_Metric_ExtensionValue:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExtensionValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Payload_Metric.Value has unexpected type %T", x)
	}
	return nil
}

func _Payload_Metric_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Payload_Metric)
	switch tag {
	case 10: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Metric_IntValue{uint32(x)}
		return true, err
	case 11: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Metric_LongValue{x}
		return true, err
	case 12: // value.float_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Payload_Metric_FloatValue{math.Float32frombits(uint32(x))}
		return true, err
	case 13: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Payload_Metric_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 14: // value.boolean_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Payload_Metric_BooleanValue{x != 0}
		return true, err
	case 15: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Payload_Metric_StringValue{x}
		return true, err
	case 16: // value.bytes_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &Payload_Metric_BytesValue{x}
		return true, err
	case 17: // value.dataset_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_DataSet)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_Metric_DatasetValue{msg}
		return true, err
	case 18: // value.template_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_Template)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_Metric_TemplateValue{msg}
		return true, err
	case 19: // value.extension_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Payload_Metric_MetricValueExtension)
		err := b.DecodeMessage(msg)
		m.Value = &Payload_Metric_ExtensionValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Payload_Metric_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Payload_Metric)
	// value
	switch x := m.Value.(type) {
	case *Payload_Metric_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Payload_Metric_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Payload_Metric_FloatValue:
		n += 1 // tag and wire
		n += 4
	case *Payload_Metric_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *Payload_Metric_BooleanValue:
		n += 1 // tag and wire
		n += 1
	case *Payload_Metric_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Payload_Metric_BytesValue:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.BytesValue)))
		n += len(x.BytesValue)
	case *Payload_Metric_DatasetValue:
		s := proto.Size(x.DatasetValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Payload_Metric_TemplateValue:
		s := proto.Size(x.TemplateValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Payload_Metric_ExtensionValue:
		s := proto.Size(x.ExtensionValue)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Payload_Metric_MetricValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Metric_MetricValueExtension) Reset()         { *m = Payload_Metric_MetricValueExtension{} }
func (m *Payload_Metric_MetricValueExtension) String() string { return proto.CompactTextString(m) }
func (*Payload_Metric_MetricValueExtension) ProtoMessage()    {}
func (*Payload_Metric_MetricValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_sparkplugB_625f8120806c536e, []int{0, 6, 0}
}

var extRange_Payload_Metric_MetricValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_Metric_MetricValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Metric_MetricValueExtension
}
func (m *Payload_Metric_MetricValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Unmarshal(m, b)
}
func (m *Payload_Metric_MetricValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Marshal(b, m, deterministic)
}
func (dst *Payload_Metric_MetricValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Metric_MetricValueExtension.Merge(dst, src)
}
func (m *Payload_Metric_MetricValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Size(m)
}
func (m *Payload_Metric_MetricValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Metric_MetricValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Metric_MetricValueExtension proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Payload)(nil), "com.cirruslink.sparkplug.protobuf.Payload")
	proto.RegisterType((*Payload_Template)(nil), "com.cirruslink.sparkplug.protobuf.Payload.Template")
	proto.RegisterType((*Payload_Template_Parameter)(nil), "com.cirruslink.sparkplug.protobuf.Payload.Template.Parameter")
	proto.RegisterType((*Payload_Template_Parameter_ParameterValueExtension)(nil), "com.cirruslink.sparkplug.protobuf.Payload.Template.Parameter.ParameterValueExtension")
	proto.RegisterType((*Payload_DataSet)(nil), "com.cirruslink.sparkplug.protobuf.Payload.DataSet")
	proto.RegisterType((*Payload_DataSet_DataSetValue)(nil), "com.cirruslink.sparkplug.protobuf.Payload.DataSet.DataSetValue")
	proto.RegisterType((*Payload_DataSet_DataSetValue_DataSetValueExtension)(nil), "com.cirruslink.sparkplug.protobuf.Payload.DataSet.DataSetValue.DataSetValueExtension")
	proto.RegisterType((*Payload_DataSet_Row)(nil), "com.cirruslink.sparkplug.protobuf.Payload.DataSet.Row")
	proto.RegisterType((*Payload_PropertyValue)(nil), "com.cirruslink.sparkplug.protobuf.Payload.PropertyValue")
	proto.RegisterType((*Payload_PropertyValue_PropertyValueExtension)(nil), "com.cirruslink.sparkplug.protobuf.Payload.PropertyValue.PropertyValueExtension")
	proto.RegisterType((*Payload_PropertySet)(nil), "com.cirruslink.sparkplug.protobuf.Payload.PropertySet")
	proto.RegisterType((*Payload_PropertySetList)(nil), "com.cirruslink.sparkplug.protobuf.Payload.PropertySetList")
	proto.RegisterType((*Payload_MetaData)(nil), "com.cirruslink.sparkplug.protobuf.Payload.MetaData")
	proto.RegisterType((*Payload_Metric)(nil), "com.cirruslink.sparkplug.protobuf.Payload.Metric")
	proto.RegisterType((*Payload_Metric_MetricValueExtension)(nil), "com.cirruslink.sparkplug.protobuf.Payload.Metric.MetricValueExtension")
}

func init() { proto.RegisterFile("sparkplugB.proto", fileDescriptor_sparkplugB_625f8120806c536e) }

var fileDescriptor_sparkplugB_625f8120806c536e = []byte{
	// 1144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0xbf, 0xbb, 0x7b, 0xd6, 0x4e, 0xdc, 0xa1, 0x50, 0xcb, 0x50, 0x91, 0x34, 0x20, 0x45,
	0x5c, 0x58, 0x22, 0xfc, 0x08, 0x21, 0x21, 0xa4, 0x50, 0x50, 0x05, 0xb4, 0x89, 0xa6, 0xa1, 0x02,
	0x01, 0xb2, 0xd6, 0xf6, 0xb8, 0x8c, 0xb2, 0x7f, 0xdd, 0x99, 0x6d, 0x71, 0x25, 0xa4, 0xbe, 0x00,
	0x17, 0x7d, 0x1a, 0x78, 0x00, 0x5e, 0x83, 0x67, 0xe0, 0x15, 0x38, 0xf3, 0xb3, 0xeb, 0x75, 0x6b,
	0x62, 0x3b, 0xe1, 0x8a, 0xdc, 0x64, 0xe6, 0xdb, 0xe3, 0xef, 0x9c, 0x39, 0x73, 0xce, 0xd9, 0x6f,
	0xa1, 0x27, 0xd2, 0x20, 0x3b, 0x4f, 0xc3, 0xfc, 0xe1, 0xf1, 0x30, 0xcd, 0x12, 0x99, 0x90, 0xfd,
	0x49, 0x12, 0x0d, 0x27, 0x3c, 0xcb, 0x72, 0x11, 0xf2, 0xf8, 0x7c, 0x58, 0x1a, 0x98, 0xe7, 0xe3,
	0x7c, 0x76, 0xeb, 0xf9, 0x4d, 0x70, 0x4e, 0x83, 0x79, 0x98, 0x04, 0x53, 0xf2, 0x26, 0x78, 0x92,
	0x47, 0x4c, 0xc8, 0x20, 0x4a, 0xfb, 0xb5, 0xbd, 0xda, 0x61, 0x93, 0x2e, 0x00, 0xf2, 0x35, 0x38,
	0x11, 0x93, 0x19, 0x9f, 0x88, 0x7e, 0x7d, 0xaf, 0x71, 0xe8, 0x1f, 0xbd, 0x37, 0x5c, 0x4b, 0x3f,
	0xb4, 0xd4, 0xc3, 0xbb, 0xfa, 0x97, 0xb4, 0x60, 0x20, 0x3d, 0x68, 0x08, 0xf6, 0xa8, 0xdf, 0xd0,
	0x4e, 0xd4, 0x92, 0x10, 0x68, 0xe6, 0x39, 0x9f, 0xf6, 0x9b, 0x08, 0x79, 0x54, 0xaf, 0x15, 0x36,
	0x4e, 0xa6, 0xf3, 0x7e, 0x0b, 0xb1, 0x0e, 0xd5, 0xeb, 0xc1, 0x5f, 0x2d, 0x70, 0xcf, 0x58, 0x94,
	0x86, 0x81, 0x64, 0xa4, 0x0f, 0xce, 0x63, 0x96, 0x09, 0x9e, 0xc4, 0x3a, 0x5e, 0x8f, 0x16, 0xdb,
	0xff, 0x36, 0xda, 0x9f, 0x00, 0xd0, 0x38, 0xc0, 0x2d, 0xb2, 0x63, 0xd0, 0x8a, 0xef, 0xd3, 0x2d,
	0xf8, 0x8a, 0x78, 0x11, 0xb0, 0x2c, 0xb4, 0x42, 0x48, 0xf6, 0xa1, 0x23, 0xad, 0xc5, 0x28, 0x63,
	0x33, 0x9b, 0x02, 0xbf, 0xc0, 0x28, 0x9b, 0x91, 0x03, 0xe8, 0x72, 0x31, 0x9a, 0xb2, 0x19, 0x8f,
	0xb9, 0x54, 0xc7, 0x55, 0x29, 0x71, 0x69, 0x87, 0x8b, 0xdb, 0x25, 0x36, 0xf8, 0xa3, 0x01, 0x5e,
	0xe9, 0x41, 0x25, 0x2f, 0xc6, 0xa5, 0x4d, 0x8c, 0x5e, 0x2b, 0x4c, 0xce, 0x53, 0x86, 0x29, 0xa9,
	0x1d, 0x76, 0xa9, 0x5e, 0x93, 0x9b, 0xe0, 0xf1, 0x58, 0x8e, 0x1e, 0x07, 0x61, 0xce, 0xf4, 0x85,
	0x74, 0xef, 0xbc, 0x42, 0x5d, 0x84, 0x1e, 0x28, 0x84, 0xbc, 0x05, 0x10, 0x26, 0xf1, 0x43, 0xfb,
	0x5c, 0x85, 0xd6, 0xc4, 0xe7, 0x9e, 0xc2, 0x8c, 0xc1, 0x3e, 0xf8, 0x33, 0x3c, 0x65, 0xc1, 0xa0,
	0x02, 0xab, 0xa3, 0x05, 0x68, 0xd0, 0x98, 0x1c, 0x40, 0x67, 0x9a, 0xe4, 0xe3, 0x90, 0x59, 0x9b,
	0x36, 0xda, 0xd4, 0xd0, 0xc6, 0x37, 0xa8, 0x31, 0x7a, 0x07, 0xba, 0xe3, 0x24, 0x09, 0x59, 0x10,
	0x5b, 0x2b, 0x47, 0x1d, 0x11, 0xad, 0x3a, 0x16, 0x2e, 0xb9, 0x04, 0xde, 0x4a, 0x19, 0x91, 0xab,
	0x8e, 0xa7, 0xb8, 0x0c, 0x6a, 0x8c, 0x9e, 0xd5, 0x60, 0x97, 0xfd, 0x22, 0x59, 0xac, 0x6a, 0xc1,
	0x1a, 0x7a, 0x68, 0xe8, 0x1f, 0x7d, 0x7b, 0xa5, 0x6b, 0x5b, 0xac, 0xb4, 0x9f, 0x2f, 0x0a, 0x17,
	0xe8, 0x7f, 0xa7, 0xf4, 0xa7, 0x1f, 0x0d, 0x0e, 0xe0, 0xc6, 0xbf, 0x18, 0xbf, 0xeb, 0xba, 0xb5,
	0xde, 0x33, 0xfc, 0xab, 0x1f, 0x3b, 0xd0, 0xd2, 0xc1, 0x21, 0xd4, 0x36, 0xd0, 0xe0, 0xf7, 0x16,
	0x38, 0xb7, 0x03, 0x19, 0xdc, 0x67, 0x92, 0xbc, 0x0d, 0x3b, 0x71, 0x1e, 0x8d, 0x92, 0xd9, 0x68,
	0x92, 0x84, 0x79, 0x14, 0x0b, 0xdb, 0x95, 0x1d, 0x44, 0x4f, 0x66, 0x9f, 0x1b, 0x4c, 0x35, 0x41,
	0xf1, 0x58, 0x95, 0x3a, 0x36, 0x81, 0xdd, 0x92, 0xeb, 0xd0, 0x52, 0x57, 0x6c, 0x4a, 0xb6, 0x4b,
	0xcd, 0x86, 0x7c, 0x05, 0xcd, 0x2c, 0x79, 0x22, 0xf0, 0x2e, 0x55, 0x1d, 0x7f, 0xb4, 0x45, 0x42,
	0x6c, 0x5c, 0x43, 0x9a, 0x3c, 0xa1, 0x9a, 0x63, 0xf0, 0xbc, 0x01, 0x1d, 0x8b, 0x9a, 0xcc, 0x2f,
	0x55, 0x53, 0x6d, 0x4d, 0x35, 0xd5, 0xd7, 0x56, 0x53, 0x63, 0x83, 0x6a, 0x6a, 0x6e, 0x54, 0x4d,
	0xad, 0x8d, 0xaa, 0xa9, 0xbd, 0x69, 0x35, 0x39, 0x5b, 0x57, 0x53, 0x91, 0xbc, 0x6a, 0xba, 0x96,
	0x36, 0x17, 0x55, 0xd3, 0x3e, 0xbc, 0xb6, 0xd2, 0x74, 0x45, 0x2d, 0x0d, 0x42, 0x68, 0xe0, 0x05,
	0x91, 0x1f, 0xc0, 0x65, 0x21, 0x8b, 0x58, 0x2c, 0x55, 0xd9, 0xa8, 0xab, 0xfe, 0xec, 0x8a, 0xd1,
	0xd2, 0x92, 0x10, 0xdd, 0xd6, 0x8d, 0x5b, 0x5c, 0xb5, 0x6c, 0xe5, 0xfe, 0xd6, 0x82, 0xee, 0x69,
	0x96, 0xa4, 0x2c, 0x93, 0x73, 0x93, 0xb8, 0x62, 0xdc, 0xd4, 0x2a, 0xe3, 0xe6, 0x06, 0x38, 0x38,
	0xc9, 0xe2, 0x3c, 0x0c, 0xf5, 0xf5, 0xbb, 0xb4, 0xcd, 0xc5, 0x3d, 0xdc, 0xfd, 0x2f, 0xe7, 0x10,
	0x83, 0x6b, 0xa9, 0xcd, 0x88, 0x60, 0x72, 0x69, 0x10, 0x6d, 0xd3, 0x77, 0x45, 0x56, 0xf1, 0x22,
	0xd0, 0x43, 0xaf, 0x42, 0x69, 0xdc, 0x9c, 0x03, 0xa9, 0x60, 0xc2, 0xfa, 0x01, 0xed, 0xe7, 0x93,
	0xcb, 0xf9, 0xf9, 0x86, 0x0b, 0xe5, 0xab, 0x1a, 0xbe, 0x30, 0xce, 0x9e, 0xbe, 0xdc, 0x0c, 0xbe,
	0xf6, 0x74, 0x72, 0x09, 0x4f, 0xa6, 0x0b, 0x96, 0x76, 0x17, 0xb5, 0xc1, 0x2d, 0x78, 0x7d, 0xb5,
	0xed, 0xaa, 0x3e, 0xf8, 0x15, 0xfc, 0xca, 0x81, 0x54, 0x31, 0x9e, 0xb3, 0xb9, 0xe9, 0x05, 0x7c,
	0x1f, 0xaa, 0x35, 0x39, 0x85, 0xb6, 0xb6, 0x2d, 0x44, 0xc2, 0xc7, 0x97, 0x3d, 0x02, 0xb5, 0x3c,
	0x18, 0x47, 0xc3, 0xb6, 0x43, 0x0e, 0xbb, 0x2f, 0xe4, 0x93, 0x7c, 0x07, 0x7e, 0x25, 0x9f, 0xb6,
	0x2b, 0x2f, 0x59, 0x08, 0xb4, 0x4a, 0xb5, 0xe8, 0xc7, 0xc1, 0xdf, 0x35, 0x70, 0x51, 0xbf, 0x04,
	0xaa, 0x71, 0xc9, 0x2d, 0x2d, 0x1b, 0xa2, 0x3c, 0x94, 0x7c, 0x84, 0xac, 0x52, 0x77, 0xa2, 0x4b,
	0x7d, 0x2e, 0xee, 0x2a, 0x0c, 0x5f, 0x50, 0x52, 0xa9, 0x8f, 0x49, 0x12, 0x63, 0x1e, 0xe5, 0xa8,
	0xd4, 0x06, 0xa8, 0x3e, 0x2c, 0x76, 0xa6, 0x7a, 0x16, 0x53, 0x27, 0xf8, 0x53, 0x66, 0xe5, 0x9a,
	0x5e, 0x17, 0x0a, 0xae, 0xb9, 0x50, 0x70, 0x6f, 0x80, 0x37, 0xe3, 0xd8, 0x5b, 0x5a, 0x75, 0xb4,
	0x34, 0x8b, 0xab, 0x80, 0x7b, 0x4a, 0x79, 0x14, 0x0f, 0xb5, 0x8b, 0xf6, 0xe2, 0xa1, 0xe6, 0x47,
	0xae, 0x68, 0xfa, 0xa1, 0x6e, 0x34, 0x8f, 0xaa, 0x25, 0xd9, 0x03, 0x7f, 0xca, 0xc4, 0x24, 0xe3,
	0xa9, 0x56, 0x3b, 0xae, 0x89, 0xa9, 0x02, 0xe1, 0x89, 0x3d, 0x7b, 0xe2, 0x3f, 0x1d, 0x68, 0x1b,
	0xc5, 0xb6, 0x52, 0xf3, 0xe0, 0x4b, 0x30, 0x08, 0x79, 0x20, 0xcc, 0xdb, 0x86, 0x9a, 0xcd, 0xb2,
	0xd6, 0x6d, 0xbc, 0xa8, 0x75, 0x07, 0xe0, 0x4e, 0x31, 0x7f, 0x3a, 0xd8, 0xa6, 0x1e, 0x5e, 0xe5,
	0xde, 0x4a, 0xb1, 0x9f, 0xf1, 0x3e, 0x13, 0x74, 0x19, 0x84, 0x0b, 0x29, 0x76, 0xa7, 0xc4, 0x54,
	0x52, 0xd1, 0x48, 0x66, 0x01, 0x56, 0x27, 0x66, 0x51, 0x9f, 0x58, 0xe7, 0xfd, 0xac, 0x80, 0xaa,
	0x83, 0xd0, 0x59, 0x1a, 0x84, 0x27, 0xe0, 0xa2, 0x6a, 0x08, 0x94, 0x43, 0x7d, 0x70, 0xff, 0xe8,
	0xfd, 0xed, 0xb4, 0xab, 0xbe, 0x7b, 0x5a, 0x92, 0x90, 0x07, 0x28, 0x5f, 0x4d, 0xad, 0x70, 0xac,
	0xf4, 0x2b, 0x8d, 0x1f, 0x5a, 0x61, 0x5a, 0x9e, 0xd8, 0xb0, 0x66, 0x62, 0xfb, 0x6b, 0x27, 0x76,
	0x67, 0x83, 0x89, 0xdd, 0xdd, 0x68, 0x62, 0xef, 0x6c, 0x34, 0xb1, 0x77, 0x57, 0x4d, 0x6c, 0x8c,
	0x69, 0x3c, 0x97, 0xac, 0x98, 0xa1, 0x3d, 0xf5, 0xe5, 0xa1, 0x62, 0xd2, 0xa0, 0x31, 0xf9, 0x1e,
	0xba, 0x2a, 0xad, 0x8b, 0x81, 0x7e, 0x4d, 0x67, 0xf4, 0x68, 0xfb, 0xb7, 0xab, 0x0a, 0xd1, 0x52,
	0x19, 0xea, 0x1f, 0x61, 0xa7, 0xfc, 0x12, 0x30, 0xdc, 0x64, 0xeb, 0x02, 0x28, 0x54, 0x2b, 0x92,
	0x77, 0x0b, 0x32, 0xc3, 0xfe, 0xe8, 0xe5, 0xc9, 0xfd, 0xaa, 0xa6, 0xff, 0x72, 0xeb, 0x6f, 0x23,
	0xfb, 0x6f, 0xed, 0xc0, 0xde, 0x83, 0xeb, 0xab, 0x2c, 0x2f, 0x94, 0xc0, 0xc7, 0x1f, 0xc0, 0xfa,
	0x0f, 0xd7, 0xe3, 0xdd, 0xfb, 0xe5, 0xd7, 0xee, 0xa9, 0xc2, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xde, 0x5d, 0x65, 0x97, 0xff, 0x0e, 0x00, 0x00,
}
